"""Deterministic defaults from development plan §21.1 (ADR-0004).

Single source for code and tests.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class LoadProfile:
    human_accounts: int = 50
    agents: int = 20
    channels: int = 100
    bridges: int = 20
    api_writes_rps: int = 20
    messages_rps: int = 10
    active_schedules: int = 100
    due_per_minute_max: int = 20
    peak_multiplier: int = 3
    peak_duration_minutes: int = 30


NORMAL_LOAD = LoadProfile()

API_WRITE_P95_MS = 500
API_READ_P95_MS = 300
API_5XX_MAX_RATIO = 0.01

AGENT_HEARTBEAT_INTERVAL_S = 30
AGENT_OFFLINE_AFTER_S = 90
AGENT_OFFLINE_MISSES = 3
AGENT_BACK_ONLINE_WITHIN_S = 30

ADAPTER_CANCEL_ACK_S = 10
ADAPTER_CANCEL_CLEANUP_S = 60

SECRET_REVOKE_CLEANUP_S = 5
SECRET_LEASE_TTL_S = 300
SECRET_LEASE_SINGLE_USE = True

DASHBOARD_FAULT_REFLECTION_S = 60

SCHEDULE_RETRY_MAX_ATTEMPTS = 3
SCHEDULE_RETRY_BACKOFF_S = (1, 5, 25)
SCHEDULE_RETRY_JITTER_MAX_RATIO = 0.20
SCHEDULE_REPLACE_CANCEL_TIMEOUT_S = 60
SCHEDULE_MIN_INTERVAL_MINUTES_DEFAULT = 5
SCHEDULE_MIN_INTERVAL_MINUTES_FLOOR = 1
SCHEDULER_POLL_S = 15
SCHEDULER_POLL_RANGE_S = (5, 60)
SCHEDULER_CLAIM_LEASE_S = 60
SCHEDULER_RUNNING_LEASE_HEARTBEAT_S = 15
SCHEDULER_LEASE_MIN_POLL_MULTIPLE = 3
SCHEDULE_START_DELAY_P95_S = 60

BACKUP_RPO_HOURS = 24
BACKUP_RTO_HOURS = 4
BACKUP_RETENTION = {"daily": 14, "weekly": 8, "monthly": 12}

WORK_ITEM_ACK_TIMEOUT_S = 60
WORK_ITEM_MAX_REDELIVERIES = 3
TASK_ASSIGNMENT_ACCEPT_TIMEOUT_S = 120
TASK_ASSIGNMENT_REROUTES = 1
WORK_ITEM_PAYLOAD_MAX_BYTES = 1_000_000

VERIFIER_ACCEPT_TIMEOUT_MIN = 10

APPROVAL_EXPIRY_HOURS = 24
APPROVAL_REMINDER_RATIO = 0.5
APPROVAL_QUORUM = {"LOW": 0, "MEDIUM": 1, "HIGH": 1, "CRITICAL": 2}

RENDERER_PROGRESS_COALESCE_S = 10
RENDERER_BODY_ARTIFACT_THRESHOLD_CHARS = 16_000

MCP_LONG_POLL_MAX_WAIT_S = 30
WEBHOOK_TIMESTAMP_WINDOW_S = 300
WEBHOOK_NONCE_RETENTION_H = 24
CALLBACK_TIMESTAMP_TOLERANCE_S = 300

COST_UNITS_PER_CREDIT = 1_000_000

MESSAGE_RETENTION_DAYS = 365

BRAINSTORM_TURNS_PER_AGENT = 5
BRAINSTORM_MAX_CONSECUTIVE = 1
BRAINSTORM_TOTAL_TURNS = 40

LINK_CHALLENGE_TTL_MIN = 10
LINK_CHALLENGE_MAX_FAILURES = 5
LINK_CHALLENGE_LOCKOUT_MIN = 15

SETUP_TOKEN_BITS = 256
SETUP_TOKEN_TTL_MIN = 30
SETUP_TOKEN_MAX_FAILURES = 5
SETUP_TOKEN_FAILURE_WINDOW_MIN = 15
SETUP_TOKEN_BLOCK_MIN = 15
SETUP_RECONFIGURE_SESSION_MIN = 30
SETUP_PRE_DB_HANDLE_TTL_MIN = 15
BREAK_GLASS_SESSION_MIN = 60
HARD_DELETE_WAIT_HOURS = 72

ACCESSIBILITY_TARGET = "WCAG 2.1 AA"
