"""One load-generator process (P7-04).

Traffic is generated by separate OS processes rather than threads: 60 writes per second with a
~70 ms service time needs several requests in flight, and threads in one interpreter would queue
behind the GIL, measuring the generator instead of the server. Each process issues its share of
the rate and writes its samples as JSON, which the harness aggregates.
"""

from __future__ import annotations

import argparse
import itertools
import json
import sys
import time
import uuid
from pathlib import Path
from typing import Any

import httpx


def _write_body(channel_uuid: str, n: int) -> dict[str, Any]:
    return {
        "title": f"load write {n}",
        "channel_id": channel_uuid,
        "domain": "research",
        "risk": "LOW",
        "criteria": [{"statement": "load", "check_type": "evidence", "required": True}],
    }


#: How often a running generator republishes its counters. A soak reads these files once a
#: minute to report cumulative traffic while the run is still going; the full sample list is only
#: written when the process exits.
PROGRESS_INTERVAL_S = 10.0


def _publish(progress: Path | None, kind: str, requests: int, errors: int) -> None:
    """Counters only, written by rename so a reader never sees a half-written file."""
    if progress is None:
        return
    tmp = progress.with_suffix(".tmp")
    try:
        tmp.write_text(
            json.dumps({"kind": kind, "requests": requests, "errors": errors}), encoding="utf-8"
        )
        tmp.replace(progress)
    except OSError:  # pragma: no cover - progress is advisory, never fatal
        pass


def generate(
    base: str,
    token: str,
    kind: str,
    rate_per_s: float,
    seconds: float,
    channels: list[str],
    progress: Path | None = None,
) -> dict[str, Any]:
    latencies: list[float] = []
    statuses: dict[str, int] = {}
    counter = itertools.count()
    interval = 1.0 / rate_per_s if rate_per_s > 0 else 0.0
    deadline = time.monotonic() + seconds
    if interval == 0.0:
        return {"kind": kind, "latency_ms": [], "statuses": {}}
    errors = 0
    next_progress = time.monotonic() + PROGRESS_INTERVAL_S
    _publish(progress, kind, 0, 0)
    with httpx.Client(base_url=base, timeout=30.0) as client:
        next_at = time.monotonic()
        while time.monotonic() < deadline:
            n = next(counter)
            channel = channels[n % len(channels)]
            started = time.perf_counter()
            try:
                if kind == "write":
                    response = client.post(
                        "/api/v1/tasks",
                        json=_write_body(channel, n),
                        headers={
                            "Authorization": f"Bearer {token}",
                            "Idempotency-Key": f"load-{uuid.uuid4().hex}",
                        },
                    )
                else:
                    response = client.get(
                        "/api/v1/tasks?limit=20", headers={"Authorization": f"Bearer {token}"}
                    )
                status = response.status_code
            except httpx.HTTPError:
                status = 599  # a transport failure counts as a server error
            latencies.append((time.perf_counter() - started) * 1000.0)
            statuses[str(status)] = statuses.get(str(status), 0) + 1
            if status >= 500:
                errors += 1
            if time.monotonic() >= next_progress:
                _publish(progress, kind, len(latencies), errors)
                next_progress = time.monotonic() + PROGRESS_INTERVAL_S
            next_at += interval
            sleep = next_at - time.monotonic()
            if sleep > 0:
                time.sleep(sleep)
            else:  # fell behind: resynchronise rather than burst
                next_at = time.monotonic()
    _publish(progress, kind, len(latencies), errors)
    return {"kind": kind, "latency_ms": latencies, "statuses": statuses}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="tests.load.generator")
    parser.add_argument("--base", required=True)
    parser.add_argument("--token", required=True)
    parser.add_argument("--kind", choices=("write", "read"), required=True)
    parser.add_argument("--rate", type=float, required=True)
    parser.add_argument("--seconds", type=float, required=True)
    parser.add_argument("--channels", required=True, help="comma-separated channel row ids")
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument("--progress", type=Path, default=None, help="counters, rewritten in place")
    args = parser.parse_args(argv)
    result = generate(
        args.base,
        args.token,
        args.kind,
        args.rate,
        args.seconds,
        args.channels.split(","),
        args.progress,
    )
    args.out.write_text(json.dumps(result), encoding="utf-8")
    return 0


if __name__ == "__main__":  # pragma: no cover - CLI
    sys.exit(main())
