"""Requirement ↔ work package ↔ Test ID traceability matrix (V-P0-10).

Usage: ``python -m tools.trace_matrix [--check] [--write]``. ``--check`` exits non-zero when any
mandatory REQ lacks a development or verification link, when any package/Test ID defined in the
plans is not back-linked to at least one REQ, when a REQ references an undefined P/V ID, or when
the generated ``docs/traceability.md`` is stale.
"""

from __future__ import annotations

import argparse
import json
import sys
from typing import TypedDict

from tools.baseline import ROOT, load_baseline, phase_of

OUT_MD = ROOT / "docs" / "traceability.md"
OUT_JSON = ROOT / "docs" / "traceability.json"


class ReqRow(TypedDict):
    text: str
    packages: list[str]
    tests: list[str]


class PkgRow(TypedDict):
    phase: int
    size: str
    prereq: list[str]
    tests: list[str]
    requirements: list[str]


class TestRow(TypedDict):
    phase: int
    subject: str
    packages: list[str]
    requirements: list[str]


class Matrix(TypedDict):
    requirements: dict[str, ReqRow]
    packages: dict[str, PkgRow]
    tests: dict[str, TestRow]
    problems: list[str]


def build() -> Matrix:
    b = load_baseline()
    problems: list[str] = []
    pkg_to_req: dict[str, list[str]] = {p: [] for p in b.packages}
    test_to_req: dict[str, list[str]] = {t: [] for t in b.tests}
    for req in b.requirements.values():
        if not req.packages:
            problems.append(f"{req.req_id}: no development package linked")
        if not req.tests:
            problems.append(f"{req.req_id}: no verification Test linked")
        for pid in req.packages:
            if pid not in b.packages:
                problems.append(f"{req.req_id}: references undefined package {pid}")
            else:
                pkg_to_req[pid].append(req.req_id)
        for tid in req.tests:
            if tid not in b.tests:
                problems.append(f"{req.req_id}: references undefined Test {tid}")
            else:
                test_to_req[tid].append(req.req_id)
    problems.extend(
        f"{p}: package not back-linked to any REQ" for p, r in pkg_to_req.items() if not r
    )
    problems.extend(
        f"{t}: Test not back-linked to any REQ" for t, r in test_to_req.items() if not r
    )
    pkg_tests: dict[str, list[str]] = {}
    for pkg in b.packages.values():
        for tid in pkg.tests:
            if tid not in b.tests:
                problems.append(f"{pkg.package_id}: references undefined Test {tid}")
            pkg_tests.setdefault(tid, []).append(pkg.package_id)
    return Matrix(
        requirements={
            r.req_id: ReqRow(text=r.text, packages=r.packages, tests=r.tests)
            for r in b.requirements.values()
        },
        packages={
            p.package_id: PkgRow(
                phase=phase_of(p.package_id),
                size=p.size,
                prereq=p.prereq,
                tests=p.tests,
                requirements=pkg_to_req[p.package_id],
            )
            for p in b.packages.values()
        },
        tests={
            t.test_id: TestRow(
                phase=phase_of(t.test_id),
                subject=t.subject,
                packages=pkg_tests.get(t.test_id, []),
                requirements=test_to_req[t.test_id],
            )
            for t in b.tests.values()
        },
        problems=problems,
    )


def render(m: Matrix) -> str:
    lines = [
        "# Traceability matrix (generated by `python -m tools.trace_matrix --write`)",
        "",
        "Source: spec Appendix A, development plan package tables, validation plan Test tables.",
        "Do not edit by hand; regenerate after any baseline change.",
        "",
        "## Requirement → packages → Tests",
        "",
        "| REQ | Packages | Tests |",
        "|---|---|---|",
    ]
    for rid, r in m["requirements"].items():
        lines.append(f"| {rid} | {', '.join(r['packages'])} | {', '.join(r['tests'])} |")
    lines += [
        "",
        "## Package → Tests → Requirements",
        "",
        "| Package | Phase | Size | Prereq | Tests | REQ |",
        "|---|---|---|---|---|---|",
    ]
    for pid, p in m["packages"].items():
        prereq = ", ".join(p["prereq"]) or "—"
        lines.append(
            f"| {pid} | {p['phase']} | {p['size']} | {prereq} | {', '.join(p['tests'])} | "
            f"{', '.join(p['requirements'])} |"
        )
    lines += [
        "",
        "## Test → Packages → Requirements",
        "",
        "| Test | Phase | Packages | REQ |",
        "|---|---|---|---|",
    ]
    for tid, t in m["tests"].items():
        lines.append(
            f"| {tid} | {t['phase']} | {', '.join(t['packages'])} | "
            f"{', '.join(t['requirements'])} |"
        )
    lines += [
        "",
        f"Requirements: {len(m['requirements'])} · Packages: {len(m['packages'])} · "
        f"Tests: {len(m['tests'])} · Problems: {len(m['problems'])}",
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--write", action="store_true")
    ns = ap.parse_args(argv)
    m = build()
    problems = list(m["problems"])
    if ns.write:
        OUT_MD.write_text(render(m), encoding="utf-8")
        OUT_JSON.write_text(json.dumps(m, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    if ns.check and OUT_MD.exists() and OUT_MD.read_text(encoding="utf-8") != render(m):
        problems.append("docs/traceability.md is stale; run --write")
    for p in problems:
        print(f"TRACE: {p}")
    print(
        f"trace_matrix: {len(m['requirements'])} REQ, {len(m['packages'])} packages, "
        f"{len(m['tests'])} tests, {len(problems)} problems"
    )
    return 1 if (ns.check and problems) else 0


if __name__ == "__main__":
    sys.exit(main())
